# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Elastic Properties Calculator (EasyPBC)', kernelModule='easypbc', kernelFunction='feasypbc', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgGroupBox(name='GroupBox_4', p='DialogBox', text='Model and analysis details', layout='0')
RsgTextField(p='GroupBox_4', fieldType='String', ncols=20, labelText='Model name', keyword='part', default='Model-1')
RsgTextField(p='GroupBox_4', fieldType='String', ncols=20, labelText='Instance name', keyword='inst', default='Part-1-1')
RsgTextField(p='GroupBox_4', fieldType='Float', ncols=10, labelText='Mapping accuracy *', keyword='meshsens', default='10E-8')
RsgTextField(p='GroupBox_4', fieldType='Float', ncols=2, labelText='Number of CPUs to be used **', keyword='CPU', default='1')
RsgLabel(p='GroupBox_4', text='*  Mesh mapping accuracy of opposite sides should be within the above value.', useBoldFont=False)
RsgLabel(p='GroupBox_4', text='** If number of CPUs exceeds the available, all available CPUs will be used.', useBoldFont=False)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='The homogenised elastic properties', layout='0')
RsgCheckButton(p='GroupBox_1', text='E11 (Young modulus in X-direction)', keyword='E11', default=True)
RsgLabel(p='GroupBox_1', text='     + Dependent V12 (Poisson ratio in XY-direction)', useBoldFont=False)
RsgLabel(p='GroupBox_1', text='     + Dependent V13 (Poisson ratio in XZ-direction) for 3D models', useBoldFont=False)
RsgCheckButton(p='GroupBox_1', text='E22 (Young modulus in Y-direction)', keyword='E22', default=True)
RsgLabel(p='GroupBox_1', text='     + Dependent V21 (Poisson ratio in YX-direction)', useBoldFont=False)
RsgLabel(p='GroupBox_1', text='     + Dependent V23 (Poisson ratio in YZ-direction) for 3D models', useBoldFont=False)
RsgCheckButton(p='GroupBox_1', text='E33 (Young modulus in Z-direction) for 3D models', keyword='E33', default=True)
RsgLabel(p='GroupBox_1', text='     + Dependent V31 (Poisson ratio in ZX-direction)', useBoldFont=False)
RsgLabel(p='GroupBox_1', text='     + Dependent V32 (Poisson ratio in ZY-direction)', useBoldFont=False)
RsgCheckButton(p='GroupBox_1', text='G12 (Shear modulus in XY-direction)', keyword='G12', default=True)
RsgCheckButton(p='GroupBox_1', text='G13 (Shear modulus in XZ-direction) for 3D models', keyword='G13', default=True)
RsgCheckButton(p='GroupBox_1', text='G23 (Shear modulus in YZ-direction) for 3D models', keyword='G23', default=True)
RsgCheckButton(p='GroupBox_1', text='If ticked, only corresponding PBC will be created, elastic properties will not be estimated.', keyword='onlyPBC', default=False)
dialogBox.show()
